---
apiVersion: v1
kind: Namespace
metadata:
  name: mariadb-prod
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: mariadb-app-prod
  namespace: mariadb-prod
spec:
  type: Git
  pathname: https://github.com/benny12332/rhacm-demo.git
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: dev-clusters
  namespace: mariadb-prod
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      stage: prod
      env: aws
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: mariadb-app-prod
  namespace: mariadb-prod
  labels:
    app: mariadb-app-prod
  annotations:
    apps.open-cluster-management.io/github-path: mariadb-resources
spec:
  channel: mariadb-prod/mariadb-app-prod
  placement:
    placementRef:
      kind: PlacementRule
      name: dev-clusters
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: mariadb-app-prod
  namespace: mariadb-prod
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - mariadb-app-prod
