---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: mariadb-app
  namespace: mariadb
spec:
  type: Git
  pathname: https://gitlab.com/michael.kot/rhacm-demo.git
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: mariadb-app
  namespace: mariadb
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - mariadb-app
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: mariadb-app
  namespace: mariadb
  labels:
    app: mariadb-app
  annotations:
    apps.open-cluster-management.io/github-path: mariadb-resources
spec:
  channel: mariadb/mariadb-app
  placement:
    placementRef:
      kind: PlacementRule
      name: dev-clusters
