apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-prod
  labels:
    app: mariadb-prod
    type: database
spec:
  selector:
    matchLabels:
      app: mariadb-prod
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb-prod
        type: database
    spec:
      containers:
        - name: mariadb
          image: quay.io/linuxserver.io/mariadb
          ports:
            - containerPort: 3306
              name: db-port
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: MYSQL_ROOT_PASSWORD
